### ISSUE TITLE
Reduce the amount of DESTROY cards

### ISSUE THREAD

**Issue by rayanii** [HammyPig/oracle#11]
The abundance of DESTROY cards makes it impossible for building cards to stay in play for more than a single round.

**Comment by rayanii** [comment]
Alternatives: Tweak DESTROY cards to serve a similar  purpose, for example, DESTROY cards can be used to destroy ALL buildings of a single building type (farm, spell tower, barracks, etc). -> Can be changed to affect ALL players or just the player it is used on.

**Comment by rayanii** [comment]
> Alternatives: Tweak DESTROY cards to serve a similar purpose, for example, DESTROY cards can be used to destroy ALL buildings of a single building type (farm, spell tower, barracks, etc). -> Can be changed to affect ALL players or just the player it is used on.

CONS:

- If a player has stacked up on a single building type like FARM, for example, they may have an abundance of cards in their hand making it impossible to make a play against them. 
- Better to use against those who less variety of building cards but more in quantity than targeting those have a variety of building cards but less in quantity.

**Comment by HammyPig** [comment]
I think DESTROY is fairly balanced at the moment. 

It is not uncommon for players to be able to have 5 or more buildings in two rounds of gameplay, so DESTROY ensures players cannot be too greedy with how many buildings they place. 

It also gives a greater reason to conserve DEFEND cards, rather than simply DEFEND every offensive card played at you.

**Comment by rayanii** [comment]
I understand, but I still feel like DESTROY should still be tweaked to be of greater disadvantage to those who are extremely buffed in a single aspect of the game (attack limit, hand limit, etc). It sort of takes away the fun to keep constantly getting your buildings destroyed, when they only give you a slight advantage.

**Comment by HammyPig** [comment]
DESTROY will be changed from discarding all buildings, to discarding all buildings of a single building type.
