### ISSUE TITLE
remove ASSASSINATE

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#13]
The card is just a better duplicate version of ATTACK. It is quite redundant as buildings already serve to increase attack limits. Also, since ATTACK is core to the game, this card would only take away from that.

(Jimmy)

**Comment by rayanii** [comment]
But it's helpful in clutch situations, for example, when you don't have enough attack limit, and if you don't kill someone, you are guaranteed to die. 

Suggestion: Perhaps just reduce the amount instead of removing it completely?

**Comment by HammyPig** [comment]
> But it's helpful in clutch situations, for example, when you don't have enough attack limit, and if you don't kill someone, you are guaranteed to die.
> 
> Suggestion: Perhaps just reduce the amount instead of removing it completely?

There are only 3 in the entire deck, so reducing the amount wouldn't be significant.

**Comment by HammyPig** [comment]
As ATTACK has been buffed due to SPELL TOWER, ASSASSINATE plays a much more tame and also unique role. It will be kept in the game.
