### ISSUE TITLE
FORT prevents other buildings being discarded with DESTROY

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#14]
This gives more importance to FORT and also makes sense thematically. May also need to think about when to play the building more.

(Bill, Jimmy)

**Comment by rayanii** [comment]
Can't defend be used against destroy? Wouldn't this make destroy too easy to counter as there are two normal cards in the deck against it? I like the thematic aspect though.

**Comment by HammyPig** [comment]
I think FORT is fine where it is. Especially since while it acts as an extra health point, it has the ability to fully block attacks which are buffed by SPELL TOWERs.
