### ISSUE TITLE
is it just me or is the game like slow and boring and repetitive

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#22]
![Alt Text](https://media.tenor.com/images/0039116a4a4f3fffa681b7ea1ab8d441/tenor.gif)

**Comment by HammyPig** [comment]
maybe add more barracks cards so people can attack more frequently

**Comment by HammyPig** [comment]
there also needs to be an element of randomness to spice things up

**Comment by rayanii** [comment]
sometimes it also depends on the people playing
