### ISSUE TITLE
non-unique building buffs shouldn't stack

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#4]
If you had two or more buildings of the same type (i.e. two farms), pile the buildings onto each other and only receive one buff. Extra buildings would only act as a buffer when another player is capturing one.

**Comment by HammyPig** [comment]
Takes a lot of the fun and craziness away from the game so wouldn't recommend. Multiple building buffs shouldn't be that bad anyway.

**Comment by rayanii** [comment]
> Takes a lot of the fun and craziness away from the game so wouldn't recommend. Multiple building buffs shouldn't be that bad anyway.

(Ray, 2021)
