### ISSUE TITLE
GOODY BAG should only draw 2 cards

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#5]
GOODY BAG drawing 3 cards can seem overpowered and perhaps too quickly drains the deck. Drawing 2 would reduce the amount of potential overflow and will make the game run cleaner.

**Comment by rayanii** [comment]
Suggestion: Remove Mega Goody Bags but keep Goody Bags to drawing 3 cards ( Also: reduce the amount of Goody Bag cards - maybe??)

**Comment by HammyPig** [comment]
> Suggestion: Remove Mega Goody Bags but keep Goody Bags to drawing 3 cards ( Also: reduce the amount of Goody Bag cards - maybe??)

Removing the amount of GOODY BAG cards would still mean a small handful of people will get more cards. Instead, reducing the amount of drawn cards directly will distribute the effect evenly.
