### ISSUE TITLE
players are able to put down cards they don't want before the end of their turn

### ISSUE THREAD

**Issue by HammyPig** [HammyPig/oracle#9]
This resolves the issue of cards feeling stuck in your hand, ensuring that gameplay is always fluid.

**Comment by rayanii** [comment]
Bad, because it allows players to pick and choose their cards. It shouldn't be that easy to get rid of them.

**Comment by rayanii** [comment]
Suggestion: If the player is unhappy with their hand, at the cost of skipping their turn, they can choose to put down the cards they don't want and pick up until hand limit. <- This is better, because it enforces a consequence for 'picking and choosing' their cards.

**Comment by HammyPig** [comment]
Potential solution #10
